version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on your host to port 80 in the client container

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dashboardAlina
      PORT: 5000
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"  # Map port 8080 on your host to port 80 in the Nginx container
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  # Optional: Use a custom Nginx configuration file if needed

volumes:
  mongodb-data:
